# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FcmToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenType', models.IntegerField(choices=[(0, 'Camera Application'), (1, 'User Application')])),
                ('token', models.TextField(blank=True, max_length=600, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookInfo', models.TextField(verbose_name='Book information')),
                ('booksPosLen', models.FloatField(blank=True, null=True, verbose_name='Book position')),
                ('readPos', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalShelfLen', models.FloatField(blank=True, null=True, verbose_name='Bookshelf total length')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mybooks',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.MyShelf'),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.MyShelf'),
        ),
    ]
