# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='bookDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mybooks',
            name='bookImgUri',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='mybooks',
            name='bookPublisher',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mybooks',
            name='bookTitle',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
